### ISSUE TITLE
Changing the `TAB` size

### ISSUE THREAD

**Issue by Green0wl** [eyelash/prism#1]
I see that in your projects concerning the `platon` editor you use a tab of 8 spaces. It seems to me that you could reduce it to 2, as shown in [Google C++ Style Guide](https://google.github.io/styleguide/cppguide.html#Horizontal_Whitespace). What do you think?

**Comment by eyelash** [comment]
You mean for the source code? I'm currently using hard tabs but GitHub displays them as 8 spaces. For me personally 2 spaces is not enough but I could add an EditorConfig file to make GitHub display the files with less indentation [like I did in some of my other projects](https://github.com/eyelash/libgral/blob/d6b676aed4d009832b859f9e0a3088f3c9b3cdfa/.editorconfig#L6).

**Comment by Green0wl** [comment]
Yes, I mean the source code. With `8` spaces, it doesn't fit the style of the code. One could just format it to `4` spaces instead of doing tricks with the `EditorConfig` file. If you think that's okay and you don't want to change anything, I'll just make the same indentation in the editor I'm working in and go with it. I wanted to consider switching to some `c++` code style standard.

**Comment by eyelash** [comment]
> Yes, I mean the source code. With 8 spaces, it doesn't fit the style of the code. One could just format it to 4 spaces instead of doing tricks with the EditorConfig file. If you think that's okay and you don't want to change anything, I'll just make the same indentation in the editor I'm working in and go with it. I wanted to consider switching to some c++ code style standard.

It's not 8 spaces, it's 1 actual tab character. You can configure your editor to display that however you like, GitHub just displays 8 spaces but my local machine displays 4 spaces. That's why I prefer tabs over spaces. Also because a tab is one byte and two spaces is two bytes.

**Comment by Green0wl** [comment]
Are you using a formatter of some kind? If yes, which one? I'd really like to decide on a formatting style.

**Comment by eyelash** [comment]
> Are you using a formatter of some kind?

I don't.
